# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/kenny/OpenCV subprograms/slant_correction"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/kenny/OpenCV subprograms/slant_correction"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/kenny/OpenCV subprograms/slant_correction/CMakeFiles" "/home/kenny/OpenCV subprograms/slant_correction/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/kenny/OpenCV subprograms/slant_correction/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slant_correction

# Build rule for target.
slant_correction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slant_correction
.PHONY : slant_correction

# fast build rule for target.
slant_correction/fast:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/build
.PHONY : slant_correction/fast

source/descriptive_stats.o: source/descriptive_stats.cpp.o

.PHONY : source/descriptive_stats.o

# target to build an object file
source/descriptive_stats.cpp.o:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/descriptive_stats.cpp.o
.PHONY : source/descriptive_stats.cpp.o

source/descriptive_stats.i: source/descriptive_stats.cpp.i

.PHONY : source/descriptive_stats.i

# target to preprocess a source file
source/descriptive_stats.cpp.i:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/descriptive_stats.cpp.i
.PHONY : source/descriptive_stats.cpp.i

source/descriptive_stats.s: source/descriptive_stats.cpp.s

.PHONY : source/descriptive_stats.s

# target to generate assembly for a file
source/descriptive_stats.cpp.s:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/descriptive_stats.cpp.s
.PHONY : source/descriptive_stats.cpp.s

source/help.o: source/help.cpp.o

.PHONY : source/help.o

# target to build an object file
source/help.cpp.o:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/help.cpp.o
.PHONY : source/help.cpp.o

source/help.i: source/help.cpp.i

.PHONY : source/help.i

# target to preprocess a source file
source/help.cpp.i:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/help.cpp.i
.PHONY : source/help.cpp.i

source/help.s: source/help.cpp.s

.PHONY : source/help.s

# target to generate assembly for a file
source/help.cpp.s:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/help.cpp.s
.PHONY : source/help.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/projection.o: source/projection.cpp.o

.PHONY : source/projection.o

# target to build an object file
source/projection.cpp.o:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/projection.cpp.o
.PHONY : source/projection.cpp.o

source/projection.i: source/projection.cpp.i

.PHONY : source/projection.i

# target to preprocess a source file
source/projection.cpp.i:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/projection.cpp.i
.PHONY : source/projection.cpp.i

source/projection.s: source/projection.cpp.s

.PHONY : source/projection.s

# target to generate assembly for a file
source/projection.cpp.s:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/projection.cpp.s
.PHONY : source/projection.cpp.s

source/slant.o: source/slant.cpp.o

.PHONY : source/slant.o

# target to build an object file
source/slant.cpp.o:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/slant.cpp.o
.PHONY : source/slant.cpp.o

source/slant.i: source/slant.cpp.i

.PHONY : source/slant.i

# target to preprocess a source file
source/slant.cpp.i:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/slant.cpp.i
.PHONY : source/slant.cpp.i

source/slant.s: source/slant.cpp.s

.PHONY : source/slant.s

# target to generate assembly for a file
source/slant.cpp.s:
	$(MAKE) -f CMakeFiles/slant_correction.dir/build.make CMakeFiles/slant_correction.dir/source/slant.cpp.s
.PHONY : source/slant.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... slant_correction"
	@echo "... source/descriptive_stats.o"
	@echo "... source/descriptive_stats.i"
	@echo "... source/descriptive_stats.s"
	@echo "... source/help.o"
	@echo "... source/help.i"
	@echo "... source/help.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/projection.o"
	@echo "... source/projection.i"
	@echo "... source/projection.s"
	@echo "... source/slant.o"
	@echo "... source/slant.i"
	@echo "... source/slant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

